import "./globals.css";
import { Lora } from "next/font/google";
import Navigation from "./Components/Navigation";
import StyledComponentsRegistry from "../registry";

const inter = Lora({ subsets: ["latin"] });

export const metadata = {
  title: "Santiago Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <Navigation />
        </StyledComponentsRegistry>
        {children}
      </body>
    </html>
  );
}
