import "./globals.css";
import Navigation from "./Components/Navigation";
import StyledComponentsRegistry from "../registry";
import { Providers } from "@/Redux/provider";

export const metadata = {
  title: "Santiago Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
        <StyledComponentsRegistry>
          <Navigation />
        </StyledComponentsRegistry>
        {children}
        </Providers>
      </body>
    </html>
  );
}
