import './globals.css'
import { Lora } from 'next/font/google'
import Navigation from "./Components/Navigation"

const inter = Lora({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}: {
  children: React.ReactNode
}) {
  return (
    
    <html lang="en">
      
      <body className={inter.className}>
        <Navigation/>
      {children}</body>
    </html>

  )
}
